version: '3.9'

# Define services
services:
  # User service
  user-service:
    image: alexvscr/microservices-user-service
    restart: always
    ports:
      - 8888:8888
#    networks:
#      - backend
    # depends_on:

  # Store service
  store-service:
    image: alexvscr/microservices-store-service
    restart: always
    ports:
      - 8080:8080
#    networks:
#      - backend
    # depends_on:

  # Orders service
  orders-service:
    image: alexvscr/microservices-orders-service
    restart: always
    ports:
      - 8081:8081
#    networks:
#      - backend
    # depends_on:

  # Cart Service
  cart-service:
    image: alexvscr/microservices-cart-service
    restart: always
    ports:
      - 8082:8082
#    networks:
#      - backend
    # depends_on:

#  networks:
#    backend: