version: '3.9'

# Define services
services:
  # User service
  user-service:
    image: alexvscr/microservices-user-service
    restart: always
    ports:
      - 8888:8888
    # depends_on:

  # Store service
  store-service:
    image: alexvscr/microservices-store-service
    restart: always
    ports:
      - 8080:8080
    # depends_on:

  # Orders service
  orders-service:
    image: alexvscr/microservices-orders-service
    restart: always
    ports:
      - 8081:8081
    # depends_on:

  # Cart Service
  cart-service:
    image: alexvscr/microservices-cart-service
    restart: always
    ports:
      - 8082:8082
    # depends_on:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_CREATE_TOPICS: "orders:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock